In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [7]:
# to generate sequence
b = np.arange(20)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
b = np.arange(10,20)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
b = np.arange(1,21).reshape(2,10)
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [25]:
b = np.arange(1,21)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [27]:
b.reshape(5,4) 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [29]:
b.reshape(2,5,2) 

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [31]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [38]:
a.shape

(20,)

In [39]:
len(a)

20

In [41]:
a.ndim

1

In [46]:
a.reshape((2,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [43]:
a.ndim

1

In [44]:
a.dtype

dtype('int32')

In [47]:
np.random.random((1,10))

array([[0.13729338, 0.06247804, 0.98629976, 0.14612288, 0.77208827,
        0.84214724, 0.01539485, 0.65385927, 0.30824627, 0.76582879]])

In [77]:
np.random.random((1,5))

array([[0.88960861, 0.85178538, 0.80100438, 0.10579265, 0.0411272 ]])

In [60]:
np.random.randint(0,10) 

6

In [69]:
g = np.random.randint(0,21,(2,5,2))

In [70]:
g

array([[[19,  3],
        [ 8, 18],
        [ 7,  8],
        [10,  0],
        [ 0,  9]],

       [[ 8, 20],
        [ 0,  1],
        [12,  0],
        [19, 12],
        [ 6,  9]]])

In [71]:
g.ndim

3

In [72]:
g.shape

(2, 5, 2)

In [73]:
g.reshape(4,5)

array([[19,  3,  8, 18,  7],
       [ 8, 10,  0,  0,  9],
       [ 8, 20,  0,  1, 12],
       [ 0, 19, 12,  6,  9]])

In [75]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [84]:
y = np.random.randint(1,3,(1,6))
y

array([[1, 1, 2, 2, 2, 2]])

In [85]:
x*y

array([[ 0,  1,  4,  6,  8, 10]])

In [86]:
x-y

array([[-1,  0,  0,  1,  2,  3]])

In [87]:
x**y

array([[ 0,  1,  4,  9, 16, 25]])

In [89]:
z = np.array([[1,2,3,4],[5,6,7,8]])
z

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [92]:
z[1]

array([5, 6, 7, 8])

In [95]:
# slicing of an array
x = np.array([[9,1,1,8],
           [8,5,7,2],
           [6,5,6,7],
           [2,4,5,6]])

x

array([[9, 1, 1, 8],
       [8, 5, 7, 2],
       [6, 5, 6, 7],
       [2, 4, 5, 6]])

In [96]:
x[:, :-1]

array([[9, 1, 1],
       [8, 5, 7],
       [6, 5, 6],
       [2, 4, 5]])

In [97]:
x[:-2, :-1]

array([[9, 1, 1],
       [8, 5, 7]])

In [98]:
x.shape

(4, 4)

In [106]:
x[::-1, :]

array([[2, 4, 5, 6],
       [6, 5, 6, 7],
       [8, 5, 7, 2],
       [9, 1, 1, 8]])

In [107]:
x[:2, :2]   #NB: :2 is row, :2 is column

array([[9, 1],
       [8, 5]])

In [108]:
x[:3, ::2]  
# i.e, print row till index 3 and  all column with step of 2

array([[9, 1],
       [8, 7],
       [6, 6]])

In [117]:
a = np.array([1,2,3,4,5,6])
a
# a.shape

array([1, 2, 3, 4, 5, 6])

In [112]:
a[:,np.newaxis]  #changing row to column
# reshape vertically by placing np.newaxis along the column


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [114]:
a[np.newaxis,:]

array([[1, 2, 3, 4, 5, 6]])

In [115]:
a.shape

(6,)

In [118]:
d = np.array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

d

# 6 rows and 1 column

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [119]:
d.shape

(6, 1)

In [121]:
s =np.array([[1, 2, 3, 4, 5, 6]])
s

# 1 row and 6 column

array([[1, 2, 3, 4, 5, 6]])

In [122]:
s.shape

(1, 6)

In [173]:
a = np.random.randint(1,5,(1,6))
a

array([[4, 2, 2, 4, 4, 3]])

In [131]:
b = np.array([[9.0,1,2],[8.0,6.0,5.0]], dtype=int)
b

array([[9, 1, 2],
       [8, 6, 5]])

In [132]:
b.ndim

2

In [133]:
b.shape

(2, 3)

In [134]:
b.dtype

dtype('int32')

In [135]:
b.itemsize

4

In [137]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [138]:
a.ndim

2

In [142]:
a.shape

(2, 7)

In [143]:
len(a)

2

In [144]:
a.size

14

In [145]:
# getting a specific row and colunm
# [r,c]

In [146]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [148]:
# getting no 6
a[0,5]
# i.e: under row 0, get me column 5

6

In [149]:
# getting no 11
a[1,3]

11

In [152]:
# i want to print the rows but stop at column 4 (5,12)

a[:,:-2]

# or

# a[:,:5]

array([[ 1,  2,  3,  4,  5],
       [ 8,  9, 10, 11, 12]])

In [153]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [154]:
# print all the rows from the end to the start 
a[::-1,:]

array([[ 8,  9, 10, 11, 12, 13, 14],
       [ 1,  2,  3,  4,  5,  6,  7]])

In [155]:
# for column
a[:,::-1]

array([[ 7,  6,  5,  4,  3,  2,  1],
       [14, 13, 12, 11, 10,  9,  8]])

In [186]:
# i want to print row 0  and column in it 
# starting from index 1 to index 6 
# but skip one step of column each
# [start index:end index:step index]
a[0,1:6:2]



array([2, 4, 6])

In [170]:
# i want to print all rows  and column in it 
# starting from index 1 to index 6 
# but skip one step of column each 
a[:,1:-1:2]

array([[ 2,  4,  6],
       [ 9, 11, 13]])

In [167]:
# print all the rows but only column 2
a[:,2]

array([ 3, 10])

In [184]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a


array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [185]:
# i want change the value of 12 to 20
a[1,4] = 20

In [180]:
print(a)

[[ 4  2  2  4 20  3]]


In [187]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 13, 14]])

In [194]:
# let say i want to replace column 2
# let say i want it all to be 50
a[:,2] = 50

# but if i want to be differentiate them
# a[:,2] = [90,70]

In [195]:
a

array([[ 1,  2, 50,  4,  5,  6,  7],
       [ 8,  9, 50, 11, 20, 13, 14]])

In [199]:
x = np.random.randint(1,50,(3,2,2))
x

array([[[21, 18],
        [27, 32]],

       [[ 1, 32],
        [41, 11]],

       [[24, 45],
        [32, 30]]])

In [200]:
# i want to get no 32
x[0,1,1]

32

In [204]:
# i want to get no 41
x[1,1,0]


41

In [205]:
x[:,:]

array([[[21, 18],
        [27, 32]],

       [[ 1, 32],
        [41, 11]],

       [[24, 45],
        [32, 30]]])

In [214]:
# i want all the rows under column 0
x[:,0]

array([[21, 18],
       [ 1, 32],
       [24, 45]])

In [217]:
# Array full of zero
# np.zeros((5))

np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [218]:
# Array full of one

np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [219]:
# Array full of your specified number

# ((shape of the array), the items u want to input)
np.full((5,6),99)

array([[99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99]])

In [235]:
# to do identity of an array
# np.eye(3)
# np.eye(5)
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [227]:
# To get random decimal numbers
np.random.rand(2,7)

array([[0.91821116, 0.90023754, 0.22728265, 0.60189911, 0.31624496,
        0.12810756, 0.554851  ],
       [0.96528092, 0.39641694, 0.22795456, 0.3019787 , 0.97540153,
        0.11687078, 0.52480346]])

In [231]:
# To get random integer numbers
np.random.randint(0,10)

7

In [234]:
# random int number with shape
# (start,end ,(shape))
np.random.randint(0,10, (2,7))

array([[8, 8, 4, 3, 9, 8, 7],
       [5, 4, 7, 8, 2, 4, 6]])

In [264]:
# To repeat an array into 2 dim
rr = np.array([[1,2,3]])
rep = np.repeat(rr, 3,axis=0 )
rep

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

# printing an array like;

# 1 1 1 1 1
# 1 0 0 0 1
# 1 0 9 0 1
# 1 0 0 0 1
# 1 1 1 1 1

# without just typing it straight

In [254]:
# solution

# printing an array of ones
arr = np.ones((5,5))
# print(arr)

# printing an array of zeros
z = np.zeros((3,3))
# print(z)

# inserting the 9

z[1,1] = 9
# print(z)

# inserting z inside arr
# arr[1:-1,1:-1] = z
# print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# printing an array like;

# 1 2 3 4 5
# 1 1 0 0 5
# 1 0 1 0 5
# 1 0 0 1 5
# 1 2 3 4 5

# without just typing it straight

In [282]:
# an array of 5 by 5
j = np.array([[1,2,3,4,5]])

# to repeat it
rep = np.repeat(j,5,axis=0)
print(rep)

# or use 

# x = np.full((5,5), [1,2,3,4,5])
# print(x)

# getting the diagonal or identity
d = np.eye(3)
print(d)
# or

# f = np.identity(3)
# print(f)

rep[1:-1, 1:-1] = d
print(rep)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 2 3 4 5]
 [1 1 0 0 5]
 [1 0 1 0 5]
 [1 0 0 1 5]
 [1 2 3 4 5]]


In [284]:
j = np.array([[1,2,3,4,5]])

x = np.full((5,5), [1,2,3,4,5])
# print(x)

d = np.eye(3)
# print(d)

x[1:-1, 1:-1] = d
print(x)

[[1 2 3 4 5]
 [1 1 0 0 5]
 [1 0 1 0 5]
 [1 0 0 1 5]
 [1 2 3 4 5]]


######  Be careful when copying arrays!!!!

In [285]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [286]:
b = a
print(b)

[1 2 3]


In [287]:
b[0] = 100
print(b)

[100   2   3]


In [288]:
a

array([100,   2,   3])

In [ ]:
# that's a wrong way to copy an array
# as u can see, u also change the values of 'a'

In [289]:
# The proper way is;
a = np.array([1,2,3])
a

array([1, 2, 3])

In [290]:
b = a.copy()
b

array([1, 2, 3])

In [291]:
b[0] = 100
b

array([100,   2,   3])

In [295]:
print(a)
print(b)

[1 2 3]
[100   2   3]



Mathematics 




In [326]:
a = np.array([1,2,3,4])
a
# sum(a)


array([1, 2, 3, 4])

In [327]:
a + 2
a

array([1, 2, 3, 4])

In [328]:
a - 2


array([-1,  0,  1,  2])

In [329]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [330]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [331]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [332]:
np.log2(a)

array([0.       , 1.       , 1.5849625, 2.       ])

In [333]:
np.cosh(a)

array([ 1.54308063,  3.76219569, 10.067662  , 27.30823284])

In [334]:
np.sum(a)

10

In [342]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

b = np.array([[2,2,2],[2,2,2]])
print(b)


[[1 2 3]
 [4 5 6]]
[[2 2 2]
 [2 2 2]]


In [346]:
c = a*b
print(c)

[[ 2  4  6]
 [ 8 10 12]]


Statistics 

In [353]:
a = np.array([[1,2,3],[4,5,6]])
a


array([[1, 2, 3],
       [4, 5, 6]])

In [349]:
np.min(a)

1

In [350]:
np.max(a)

6

In [351]:
np.mean(a)

3.5

In [352]:
np.median(a)

3.5

In [358]:
np.sum(a)

21

reorganizing Arrays

In [360]:
before = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
before

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [361]:
after =before.reshape(3,4)
after

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [362]:
after =before.reshape(2,3,2)
after

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [363]:
after =before.reshape(6,2)
after

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [369]:
# vstacking
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

c = np.vstack((a,b))
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [370]:
# horizontal stacking
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

c = np.hstack((a,b))
c

array([1, 2, 3, 4, 5, 6, 7, 8])

LOADING DATA FROM FILE

In [6]:
x = np.random.randint(1,50, (6,5))
x

array([[ 3, 46,  2, 23, 31],
       [45, 20, 25, 32, 11],
       [ 2, 32,  2, 42, 48],
       [25, 10, 37, 14, 35],
       [10, 37,  3, 29,  9],
       [35,  6, 41,  2, 37]])

In [7]:
# get [2, 32]
#     [25, 10]

x[2:-2,0:2]

array([[ 2, 32],
       [25, 10]])

In [8]:
# get [29, 9]
#     [2, 37]

x[4:,3:]

array([[29,  9],
       [ 2, 37]])

In [17]:
# to get the diagonal [46,25,42,35]

x[[0,1,2,3],[1,2,3,4]]

array([46, 25, 42, 35])

In [12]:
x[[0],[1]]

array([46])

In [13]:
x[[1],[2]]

array([25])

In [14]:
x[[2],[3]]

array([42])

In [15]:
x[[3],[4]]

array([35])

In [16]:
x[[0,1,2,3],[1,2,3,4]]

array([46, 25, 42, 35])

Assignment 2
#use us_births data to compute the following using np: #extract the year, gender and births column from the data #compute the aggregation of sum of total birth, sum of female birth and sum of male birth, mean and median #compute the maximum births and minimum births #indicate the gender with minimum birth and maximum birth #indicate the year with minimum birth and maximum birth

In [1]:
import numpy as np
import pandas as pd
import sys

us_births = pd.read_csv('C:\\Datasets\\us_births.csv')

np.set_printoptions(threshold=sys.maxsize)
us_births

year  month  day gender  births
0      1969      1  1.0      F    4046
1      1969      1  1.0      M    4440
2      1969      1  2.0      F    4454
3      1969      1  2.0      M    4548
4      1969      1  3.0      F    4548
...     ...    ...  ...    ...     ...
15542  2008     10  NaN      M  183219
15543  2008     11  NaN      F  158939
15544  2008     11  NaN      M  165468
15545  2008     12  NaN      F  173215
15546  2008     12  NaN      M  181235

[15547 rows x 5 columns]

In [5]:
#extract the year

years = np.array(us_births['year'])
print(f"The years are: '\n' {years} ")

The years are: '
' [1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969
 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969
 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969
 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969
 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969
 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969
 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969
 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969
 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969
 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969
 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969
 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969
 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969
 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 1969 19

In [6]:
# for genders

genders = np.array(us_births['gender'])
print(f"The genders are:'\n' {genders}")

The genders are:'
' ['F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M'
 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M'
 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M'
 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M'
 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M'
 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M'
 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M'
 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M'
 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M'
 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M'
 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M'
 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M'
 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M'
 'F' 'M' 'F' 'M' 'F' 'M' 'F' 'M

In [7]:
# For births

births = np.array(us_births['births'])
print(f"The births are:'\n' {births}")

The births are:'
' [  4046   4440   4454   4548   4548   4994   4440   4520   4192   4198
   4710   4850   4646   5092   4800   4934   4592   4842   4852   5190
   4580   4598   4126   4324   4758   5076   5070   5296   4798   5096
   4790   4872   4944   5030   4670   4642   4170   4452   4884   4924
   5042   5432   4796   5088   4794   4660   4752   5046   4348   4674
   4230   4338   4864   5046   4860   5172   4500   4880   4668   5006
   4780   4912     26     38   4394   4736   4334   4480   4878   5110
   4796   5200   4674   5002   4760   4968   4940   5162   4626   4636
   4252   4442   4958   4996   4796   5060   4780   5228   4850   4756
   5092   5262   4598   4712   4118   4416   4768   5054   4962   5214
   4788   5028   4920   5062   4940   4976   4484   4668   4298   4406
   4798   5168   5196   5370   4838   5210   4588   5030   4792   4964
     50     16     24     28     24     20     42     48   4402   4784
   4204   4376   4874   5194   4994   5270   4958   5088  

In [8]:
# sum of births 

print(f"Sum of total birth is: {np.sum(births )}")

Sum of total birth is: 151774378


In [18]:
# sum of female births 

female = np.sum(us_births=='F')
female



year         0
month        0
day          0
gender    7776
births       0
dtype: int64

In [19]:
# sum of male birth

male = us_births['gender'].value_counts()
total_male = male.get('M',0)
print('Total male birth: ', total_male)

Total male birth:  7771


In [25]:
print(births.min())

1


In [26]:
print(births.max())

199622


In [29]:
print(us_births.max())

year        2008
month         12
day         99.0
gender         M
births    199622
dtype: object


NameError: name 'gender' is not defined

In [31]:
print(us_births.min())

year      1969
month        1
day        1.0
gender       F
births       1
dtype: object


Assignment 1
Generate an np array of (a) vector of lenght 50 (b) two dimension of shape 5x4. Both uniformly distributed between 0 and 1 Split the two dimension array in 1 above into three arrays taking the first two rows, follow by the next two rows and put the remaining row in another variable Split the vector in 1 above into three arrays by taking the first 15, follow by the next 20 and the remaining into another variable. Create a 4x5 array: (a). Using manual method (b). Using randomly generated value between 0 and 1 (c). Using array of ones

Assignment 2
#use us_births data to compute the following using np: #extract the year, gender and births column from the data #compute the aggregation of sum of total birth, sum of female birth and sum of male birth, mean and median #compute the maximum births and minimum births #indicate the gender with minimum birth and maximum birth #indicate the year with minimum birth and maximum birth

Assignment 3
Using the BicycleWeather.csv dataset perform the following operations: 1. Extract the PRCP column from the pandas object. 2. Using boolean functions/operators separate numbers from NAN 3. Using boolean masking separate all zeros and non-zeros into different variables. 4. From the variable holding non-zeros, multiply every values in the array with 100 and divid by 250 5. Calculate the following: a. Median precip on rainy days b. Median precip on summer days c. Maximum precip on summer days d. Median precip on non-summer rainy days

# Assignment 1 solution

In [3]:
# Generate an np array of (a) vector of lenght 50

import numpy as np


In [22]:
vector = np.random.rand(50)
vector

array([0.91630143, 0.24266962, 0.90243576, 0.10893534, 0.79307672,
       0.03134441, 0.00504199, 0.24665638, 0.27175982, 0.98018981,
       0.92041732, 0.79815478, 0.45056365, 0.30063284, 0.07578995,
       0.07747073, 0.31256002, 0.3631008 , 0.92368224, 0.12703454,
       0.16507349, 0.71380835, 0.2573751 , 0.55395455, 0.2779444 ,
       0.09811038, 0.97313149, 0.00348131, 0.97888605, 0.44747556,
       0.79668895, 0.96257617, 0.33822691, 0.81453268, 0.35616226,
       0.3007049 , 0.62206905, 0.99053372, 0.70544061, 0.86912962,
       0.72481745, 0.65499781, 0.72602756, 0.1923439 , 0.38504765,
       0.79938888, 0.51191784, 0.1971919 , 0.38020444, 0.68391479])

In [29]:
#  two dimension of shape 5x4
dim_2 = np.random.randint(0,2,(5,4))
dim_2

array([[1, 1, 0, 1],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 1, 0]])

In [31]:
f1 = dim_2[:2,:] 
# f1
f2 = dim_2[2:4,:]
# f2
f3 = dim_2[]

array([[0, 0, 0, 1],
       [0, 1, 0, 1]])

In [2]:
import numpy as np

In [9]:
arr = np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
y  = np.zeros((3,3))
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
y[1,1] = 1
y


array([[0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.]])

In [10]:
arr[1:-1,1:-1] = y
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 1., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
arr = np.random.randint(0,20,(4,5))
arr

array([[ 7,  8,  4,  7,  7],
       [16, 16, 12, 15,  7],
       [ 0,  3,  7,  8,  1],
       [ 0, 18,  1, 15, 12]])

In [13]:
arr[2:-1,1:3]

array([[3, 7]])

In [16]:
arr[2:-1,1:3] = (4,5)
arr

array([[ 7,  8,  4,  7,  7],
       [16, 16, 12, 15,  7],
       [ 0,  4,  5,  8,  1],
       [ 0, 18,  1, 15, 12]])